/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatchImageImportDialog: typeof import('./components/BatchImageImportDialog.vue')['default']
    BatchImportDialog: typeof import('./components/BatchImportDialog.vue')['default']
    BatchUpdateDialog: typeof import('./components/BatchUpdateDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ImageUploader: typeof import('./components/common/ImageUploader.vue')['default']
    MechanicalBatchImportDialog: typeof import('./components/MechanicalBatchImportDialog.vue')['default']
    MechanicalRequisitionDialog: typeof import('./components/MechanicalRequisitionDialog.vue')['default']
    MechanicalSparePartFormDialog: typeof import('./components/MechanicalSparePartFormDialog.vue')['default']
    NaiveApiProvider: typeof import('./components/common/NaiveApiProvider.vue')['default']
    RequisitionDialog: typeof import('./components/RequisitionDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SparePartFormDialog: typeof import('./components/SparePartFormDialog.vue')['default']
    SparePartImages: typeof import('./components/sparePart/SparePartImages.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const BatchImageImportDialog: typeof import('./components/BatchImageImportDialog.vue')['default']
  const BatchImportDialog: typeof import('./components/BatchImportDialog.vue')['default']
  const BatchUpdateDialog: typeof import('./components/BatchUpdateDialog.vue')['default']
  const HelloWorld: typeof import('./components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
  const ImageUploader: typeof import('./components/common/ImageUploader.vue')['default']
  const MechanicalBatchImportDialog: typeof import('./components/MechanicalBatchImportDialog.vue')['default']
  const MechanicalRequisitionDialog: typeof import('./components/MechanicalRequisitionDialog.vue')['default']
  const MechanicalSparePartFormDialog: typeof import('./components/MechanicalSparePartFormDialog.vue')['default']
  const NaiveApiProvider: typeof import('./components/common/NaiveApiProvider.vue')['default']
  const RequisitionDialog: typeof import('./components/RequisitionDialog.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SparePartFormDialog: typeof import('./components/SparePartFormDialog.vue')['default']
  const SparePartImages: typeof import('./components/sparePart/SparePartImages.vue')['default']
  const TheWelcome: typeof import('./components/TheWelcome.vue')['default']
  const WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
}